#ifndef CONSTANTS_H
#define CONSTANTS_H

#define NOT_CONSTANT 1000000
#define NO_RETURN -100
#define NO_LABEL -200
#define __NONE__ -1

#define SOURCE_FILE "io/test/void.expl"
#define INTERMEDIATE_FILE "io/intermediate.xsm"
#define TRANSLATED_FILE "io/translated.xsm"

#define STACK_START 4096
#define STACK_END 5119
#define CODE_START 2056
#define NUM_STATIC_VARS 26
#define HEADER_SIZE 8

#define regIndex int

#define TOTAL_REGISTERS 20

typedef enum {
    INT_SIZE = 1,
    STRING_SIZE = 1,
    NONE_SIZE = 0,
    VOID_SIZE = 0
} Size;

typedef enum {
    INT,
    STRING,
    BOOL,
    TUPLE,
    VOID,
    NONE
} Type;

typedef enum {
    NODE_EMPTY,
    NODE_ASSIGN,
    NODE_CONNECTOR,

    NODE_PARAM,
    NODE_POINTER_PARAM,

    NODE_FUNC_DECL,
    NODE_FUNC_DEF,
    NODE_FUNC_CALL,
    NODE_LOCAL_DECL,
    NODE_RETURN,

    NODE_TUPLE_DECL,
    NODE_TUPLE_ACCESS,
    NODE_TUPLE_POINTER_ACCESS,
    NODE_TUPLE_ASSIGN,
    NODE_TUPLE_POINTER_ASSIGN,
    NODE_TUPLE_VAR_DECL,
    NODE_TUPLE_PARAM,
    NODE_TUPLE_POINTER_PARAM,

    NODE_BREAK_POINT,

    NODE_VARIABLE,
    NODE_CONSTANT,
    NODE_STRING_LITERAL,

    NODE_TYPE,
    NODE_DECL,

    NODE_ARRAY_DECL,
    NODE_ARRAY_ASSIGN,
    NODE_ARRAY_ACCESS,

    NODE_DEREFERENCE,
    NODE_ADDRESS_TO,
    NODE_ASSIGN_TO_DEREFERENCED,

    NODE_INC,
    NODE_DEC,

    NODE_READ,
    NODE_READ_TO_ARRAY,
    NODE_WRITE,

    NODE_GT,
    NODE_GE,
    NODE_EQ,
    NODE_NE,
    NODE_LE,
    NODE_LT,

    NODE_OR,
    NODE_AND,
    NODE_NOT,
    
    NODE_WHILE,
    NODE_BREAK,
    NODE_CONTINUE,
    NODE_REPEAT_UNTIL,
    NODE_DO_WHILE,

    NODE_IF_ELSE,
    NODE_IF,

    NODE_ADD,
    NODE_SUB,
    NODE_MUL,
    NODE_DIV,
    NODE_MOD
} NodeType;

#define SUCCESS 0
#define FAILURE -1

// errors
enum errors {
    E_VARIABLE_REDECLARATION,
    E_VARIABLE_USED_BEFORE_DECLARATION,
    E_DEREFERENCING_NON_POINTER_VARIABLE,
    E_POINTER_TO_POINTER,
    E_STACK_MEMORY_EXHAUSTED,
    E_INVALID_ARGUMENT,
    
    // function errors
    E_FUNCTION_REDECLARATION,
    E_FUNCTION_USED_BEFORE_DECLARATION,
    E_FUNCTION_SIGNATURE_TYPE_MISMATCH,
    E_FUNCTION_SIGNATURE_VARNAME_MISMATCH,
    E_FUNCTION_SIGNATURE_RETURN_TYPE_MISMATCH,
    E_FUNCTION_SIGNATURE_NUM_ARGS_MISMATCH,
    E_FUNCTION_SIGNATURE_TOO_FEW_ARG,
    E_FUNCTION_SIGNATURE_MORE_ARG,
    E_PARAMETER_DUPLICATION,
    E_FUNCTION_RETURN_TYPE_MISMATCH,
    E_FUNCTION_PASSED_ARG_MISMATCH,
    E_FUNCTION_CALL_TOO_FEW_ARG,
    E_FUNCTION_CALL_MORE_ARG,

    // tuple errors
    E_ACCESS_NON_EXISTING_FIELD_OF_TUPLE,
    E_DEREFERENCE_NON_POINTER_TUPLE,
    E_TUPLE_TYPE_USED_BEFORE_DECLARATION,
    E_TUPLE_TYPE_REDECLARATION,

    // register errors
    E_INVALID_REGISTER,
    E_NO_FREE_REGISTERS,

    E_NO_SOURCE_FILE,

    E_VARIABLE_WITH_TYPE_VOID,

    E_TYPE_MISMATCH
};

// error returns for labels
#define E_LABEL_EXISTS -3

#endif