#ifndef ERROR_HANDLER_H
#define ERROR_HANDLER_H

enum Error {
    // Source / Compiler Setup Errors
    E_NO_SOURCE_FILE = 100,

    // Variable / Symbol Table Errors
    E_VARIABLE_REDECLARATION = 200,
    E_VARIABLE_USED_BEFORE_DECLARATION,
    E_VARIABLE_WITH_TYPE_VOID,
    E_STACK_MEMORY_EXHAUSTED,

    // General Type Errors
    E_TYPE_MISMATCH = 300,
    E_ASSIGN_TYPE_MISMATCH,
    E_INVALID_ARGUMENT,

    // Pointer / Memory Errors
    E_DEREFERENCING_NON_POINTER_VARIABLE = 400,
    E_DEREFERENCE_NON_POINTER_TUPLE,
    E_POINTER_TO_POINTER,

    // Function Declaration / Definition Errors
    E_FUNCTION_REDECLARATION = 500,
    E_FUNCTION_USED_BEFORE_DECLARATION,
    E_FUNCTION_SIGNATURE_TYPE_MISMATCH,
    E_FUNCTION_SIGNATURE_VARNAME_MISMATCH,
    E_FUNCTION_SIGNATURE_RETURN_TYPE_MISMATCH,
    E_FUNCTION_SIGNATURE_NUM_ARGS_MISMATCH,
    E_FUNCTION_SIGNATURE_TOO_FEW_ARG,
    E_FUNCTION_SIGNATURE_MORE_ARG,
    E_PARAMETER_DUPLICATION,
    E_FUNCTION_RETURN_TYPE_MISMATCH,

    // Function Call Errors
    E_FUNCTION_PASSED_ARG_MISMATCH = 600,
    E_FUNCTION_CALL_TOO_FEW_ARG,
    E_FUNCTION_CALL_MORE_ARG,

    // Tuple Errors
    E_TUPLE_TYPE_USED_BEFORE_DECLARATION = 700,
    E_TUPLE_TYPE_REDECLARATION,
    E_ACCESS_NON_EXISTING_FIELD_OF_TUPLE,

    // User-Defined Type Errors
    E_USER_TYPE_REDECLARATION = 800,
    E_USER_TYPE_USED_BEFORE_DECLARATION,
    E_FIELD_TYPE_UNDEFINED,
    E_MEMBER_ACCESS_ON_NON_SUPPORTED_TYPE,
    E_ACCESS_NON_EXISTING_FIELD_OF_TYPE,
    E_INVALID_SIZE_FOR_USER_DEFINED_TYPE,
    E_USER_DEF_VAR_SIZE_OVERFLOW,

    // Register / Code Generation Errors
    E_INVALID_REGISTER = 900,
    E_NO_FREE_REGISTERS
};


void compilerError(enum Error error, ...);

#endif